# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"UCREL_API": "00_api.ipynb",
         "UCREL_Token": "01_ucrel_token.ipynb",
         "UCREL_Doc": "02_ucrel_doc.ipynb"}

modules = ["api.py",
           "ucrel_token.py",
           "ucrel_doc.py"]

doc_url = "https://UCREL.github.io/ucrel-python-api/"

git_url = "https://github.com/UCREL/ucrel-python-api/tree/main/"

def custom_doc_links(name): return None
